name: Linting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn & Eslint
        run: npm install -g yarn eslint

      - name: Install Dependencies
        run: yarn

      - name: Run Eslint Checking
        run: eslint . --ext .js,.jsx,.ts,.tsx
